### ISSUE TITLE
Citation

### ISSUE THREAD

**Issue by t-davidson** [gfleetwood/crowd-flower-hate-speech#1]
Hi Gordon,

I came across your app and blog post. It turns out that CrowdFlower released these data that myself and colleagues have been working on (and paid to get labelled) without either notifying or acknowledging us. We are academic researchers and used the CF service to get these labels to work some research projects studying hate speech. It was a bit of a shock to us to find out that these data had been released.

We would really appreciate it if you could include a link in your app and on this repo to our paper based on these data. The citation is below. It would be great if you could link to the pre-print of the paper on Arxiv: https://arxiv.org/abs/1703.04009

Thomas Davidson, Dana Warmsley, Michael Macy, and Ingmar Weber. 2017. "Automated Hate Speech Detection and the Problem of Offensive Language." Proceedings of the AAAI 11th International Conference on Web and Social Media (ICWSM). 

In the coming weeks we will also be releasing a new version of the data containing even more tweets (approx. 24k). I'll let you know when we do so as I'm sure the additional data would help improve the performance of your app.

Thanks,
Tom

**Comment by gfleetwood** [comment]
Hey Tom,

Sorry to hear about that. I added the relevant info to the README and the About page of the app. Looking forward to the bigger data set.

Best,
Gordon

**Comment by t-davidson** [comment]
Awesome, thanks. Will let you know as soon as its ready.
